[2023-10-15T11:27:08.621-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2023-10-10T14:20:00+00:00 [queued]>
[2023-10-15T11:27:08.627-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2023-10-10T14:20:00+00:00 [queued]>
[2023-10-15T11:27:08.627-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-15T11:27:08.655-0300] {taskinstance.py:1327} INFO - Executing <Task(DatabricksRunNowOperator): Extraindo-conversoes> on 2023-10-10 14:20:00+00:00
[2023-10-15T11:27:08.659-0300] {standard_task_runner.py:57} INFO - Started process 28544 to run task
[2023-10-15T11:27:08.662-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Extraindo-conversoes', 'scheduled__2023-10-10T14:20:00+00:00', '--job-id', '136', '--raw', '--subdir', 'DAGS_FOLDER/extraindo-taxas.py', '--cfg-path', '/tmp/tmpj2ukw2x7']
[2023-10-15T11:27:08.664-0300] {standard_task_runner.py:85} INFO - Job 136: Subtask Extraindo-conversoes
[2023-10-15T11:27:08.717-0300] {task_command.py:410} INFO - Running <TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2023-10-10T14:20:00+00:00 [running]> on host DESKTOP-L4GJ4I7.
[2023-10-15T11:27:08.765-0300] {abstractoperator.py:593} ERROR - Exception rendering Jinja template for task 'Extraindo-conversoes', field 'json'. Template: {'job_id': '307543230213856', 'notebook_params': {'data_execucao': '{{data_interval_end.strftime("%Y-%m-%d)}}'}}
Traceback (most recent call last):
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 585, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 29
[2023-10-15T11:27:08.766-0300] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1407, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 1531, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 2179, in render_templates
    original_task.render_template_fields(context)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 1254, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/utils/session.py", line 76, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/models/abstractoperator.py", line 585, in _do_render_template_fields
    rendered_content = self.render_template(
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in render_template
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 168, in <dictcomp>
    return {k: self.render_template(v, context, jinja_env, oids) for k, v in value.items()}
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/airflow/template/templater.py", line 155, in render_template
    template = jinja_env.from_string(value)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/jinja2/environment.py", line 1105, in from_string
    return cls.from_code(self, self.compile(source), gs, None)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/jinja2/environment.py", line 768, in compile
    self.handle_exception(source=source_hint)
  File "/home/tinoco/airflow-databricks/curso_datAir/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<unknown>", line 1, in template
jinja2.exceptions.TemplateSyntaxError: unexpected char '"' at 29
[2023-10-15T11:27:08.770-0300] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=Executando-notebook-etl, task_id=Extraindo-conversoes, execution_date=20231010T142000, start_date=20231015T142708, end_date=20231015T142708
[2023-10-15T11:27:08.798-0300] {standard_task_runner.py:104} ERROR - Failed to execute job 136 for task Extraindo-conversoes (unexpected char '"' at 29; 28544)
[2023-10-15T11:27:08.834-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-10-15T11:27:08.847-0300] {taskinstance.py:2651} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2023-10-15T20:03:45.116-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2023-10-10T14:20:00+00:00 [queued]>
[2023-10-15T20:03:45.122-0300] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2023-10-10T14:20:00+00:00 [queued]>
[2023-10-15T20:03:45.122-0300] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-10-15T20:03:45.152-0300] {taskinstance.py:1327} INFO - Executing <Task(DatabricksRunNowOperator): Extraindo-conversoes> on 2023-10-10 14:20:00+00:00
[2023-10-15T20:03:45.155-0300] {standard_task_runner.py:57} INFO - Started process 17071 to run task
[2023-10-15T20:03:45.159-0300] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'Executando-notebook-etl', 'Extraindo-conversoes', 'scheduled__2023-10-10T14:20:00+00:00', '--job-id', '286', '--raw', '--subdir', 'DAGS_FOLDER/extraindo-taxas.py', '--cfg-path', '/tmp/tmpo47vqixq']
[2023-10-15T20:03:45.161-0300] {standard_task_runner.py:85} INFO - Job 286: Subtask Extraindo-conversoes
[2023-10-15T20:03:45.217-0300] {task_command.py:410} INFO - Running <TaskInstance: Executando-notebook-etl.Extraindo-conversoes scheduled__2023-10-10T14:20:00+00:00 [running]> on host DESKTOP-L4GJ4I7.
[2023-10-15T20:03:45.335-0300] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='Executando-notebook-etl' AIRFLOW_CTX_TASK_ID='Extraindo-conversoes' AIRFLOW_CTX_EXECUTION_DATE='2023-10-10T14:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-10-10T14:20:00+00:00'
[2023-10-15T20:03:45.348-0300] {base.py:73} INFO - Using connection ID 'databricks_default' for task execution.
[2023-10-15T20:03:45.369-0300] {databricks_base.py:497} INFO - Using token auth.
[2023-10-15T20:03:45.995-0300] {databricks.py:54} INFO - Run submitted with run_id: 826906473676226
[2023-10-15T20:03:45.996-0300] {databricks_base.py:497} INFO - Using token auth.
[2023-10-15T20:03:46.527-0300] {databricks_base.py:497} INFO - Using token auth.
[2023-10-15T20:03:47.056-0300] {databricks.py:95} INFO - Extraindo-conversoes in run state: {'life_cycle_state': 'RUNNING', 'result_state': '', 'state_message': ''}
[2023-10-15T20:03:47.056-0300] {databricks.py:96} INFO - View run status, Spark UI, and logs at https://adb-343886000386578.18.azuredatabricks.net/?o=343886000386578#job/307543230213856/run/826906473676226
[2023-10-15T20:03:47.056-0300] {databricks.py:97} INFO - Sleeping for 30 seconds.
[2023-10-15T20:04:17.087-0300] {databricks_base.py:497} INFO - Using token auth.
[2023-10-15T20:04:17.645-0300] {databricks.py:65} INFO - Extraindo-conversoes completed successfully.
[2023-10-15T20:04:17.645-0300] {databricks.py:66} INFO - View run status, Spark UI, and logs at https://adb-343886000386578.18.azuredatabricks.net/?o=343886000386578#job/307543230213856/run/826906473676226
[2023-10-15T20:04:17.650-0300] {taskinstance.py:1345} INFO - Marking task as SUCCESS. dag_id=Executando-notebook-etl, task_id=Extraindo-conversoes, execution_date=20231010T142000, start_date=20231015T230345, end_date=20231015T230417
[2023-10-15T20:04:17.710-0300] {local_task_job_runner.py:225} INFO - Task exited with return code 0
[2023-10-15T20:04:17.725-0300] {taskinstance.py:2651} INFO - 1 downstream tasks scheduled from follow-on schedule check
